### ISSUE TITLE
[Bug] Cannot Create Troop

### ISSUE THREAD

**Issue by Crowguard** [reyzor1991/pf2e-troops-helper#1]
Pretty self-explanatory; neither the button or the included macro work. Both result in the same error in the console.

![Foundry_Virtual_Tabletop_NUaSoRx8SK](https://github.com/user-attachments/assets/7210b207-de8d-4468-8c86-e1bb9aa7bb8a)

https://github.com/user-attachments/assets/6065c88c-9762-4f14-a61e-7c4abe35bfe5

Foundry 12.331
PF2 6.5.1
Troop Helper 1.0.2
![Foundry_Virtual_Tabletop_UBYwBDUMvv](https://github.com/user-attachments/assets/fc8c0e4b-ea95-4b76-9882-5f883bd0ecc4)

**Comment by Crowguard** [comment]
Confirmed it is not one of the library mods; just in case.


https://github.com/user-attachments/assets/47178a65-3ded-447f-ae29-64bd8ff7872e

**Comment by Crowguard** [comment]
Fun fact; this does work when installed on Forge. I'm guessing they've cached a working version, and this module possibly had a version re-released with the same version number?

https://github.com/user-attachments/assets/8b4e51d4-8075-4d7c-9736-73492e088693

**Comment by reyzor1991** [comment]
Fixed 1.0.3
